//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP_CardAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public string ID { get; set; }
        public Nullable<int> cardID { get; set; }
        public Nullable<decimal> value { get; set; }
    
        public virtual Cards Cards { get; set; }
    }
}
